services:
  jr-auto:
    image: elbromasmc/jr-auto
    restart: no
    volumes:
      - onedrive-data:/home/runner/.config/onedrive
      - jr-auto-data:/home/runner/data
    environment:
      - DATA_DIR=/home/runner/data
      - ENV=prod
      - EXPORT_DIR=${EXPORT_DIR}
      - INCREMENTAL=${INCREMENTAL}

volumes:
  onedrive-data:
  jr-auto-data:

