services:
  jr-auto:
    image: elbromasmc/jr-auto
    volumes:
      - onedrive-data:/home/runner/.config/onedrive
      - jr-auto-data:/home/runner/data
    restart: no
    ipc: host
    security_opt:
      - seccomp:./seccomp_profile.json
    environment:
      - DATA_DIR=/home/runner/data
      - ENV=prod
      - EXPORT_DIR=${EXPORT_DIR}
      - INCREMENTAL=${INCREMENTAL}

volumes:
  onedrive-data:
  jr-auto-data:

