FROM ubuntu:oracular


RUN apt-get update \
    && apt-get install -y \
    python3 \
    python3-venv \
    curl \
    && apt-get install -y --no-install-recommends \
    git \
    openssh-client \
    gpg \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN wget -qO - \
    https://download.opensuse.org/repositories/home:/npreining:/debian-ubuntu-onedrive/xUbuntu_24.10/Release.key \
    | gpg --dearmor \
    | tee /usr/share/keyrings/obs-onedrive.gpg \
    > /dev/null \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/obs-onedrive.gpg] https://download.opensuse.org/repositories/home:/npreining:/debian-ubuntu-onedrive/xUbuntu_24.10/ ./" \
    | tee /etc/apt/sources.list.d/onedrive.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends --no-install-suggests \
    onedrive

# Use venv to install Playwright dependencies
WORKDIR /playwright

RUN python3 -m venv venv \
    && . venv/bin/activate \
    && pip install playwright \
    && playwright install-deps chromium \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /playwright

# Create and change to non-root user
RUN groupadd --gid 1001 devrunner \
    && useradd --uid 1001 --gid 1001 -m devrunner

# Change to non-root user and enter home directory
USER devrunner

# Create and enter src folder
RUN mkdir /home/devrunner/src
WORKDIR /home/devrunner/src

# Install dependencies
RUN python3 -m venv venv \
    && . venv/bin/activate \
    && pip install playwright \
    pandas \
    xlrd \
    openpyxl \
    && playwright install chromium

# Move temporally venv folder
RUN mv venv ../

# Create runtime dir
ENV XDG_RUNTIME_DIR=/tmp/runtime-dir
RUN mkdir $XDG_RUNTIME_DIR \
    && chmod 0700 $XDG_RUNTIME_DIR

# Create data folders
RUN mkdir -p /home/devrunner/.config/onedrive
RUN mkdir /home/devrunner/data

COPY --chown=devrunner:devrunner ./scripts/docker-run-dev.sh /home/devrunner/
ENTRYPOINT ["/home/devrunner/docker-run-dev.sh"]

