services:
  devrunner:
    userns_mode: "keep-id:uid=1001,gid=1001"
    image: devrunner-jr-auto
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      # Bind source directory
      - type: bind
        source: ./
        target: /home/devrunner/src
      # Bind display
      - type: bind
        source: ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}
        target: /tmp/runtime-dir/${WAYLAND_DISPLAY}
        read_only: true
      - type: bind
        source: /tmp/.X11-unix/X0
        target: /tmp/.X11-unix/X0
        read_only: true
      # Persistent data
      - dev-onedrive-data:/home/devrunner/.config/onedrive
      - dev-jr-auto-data:/home/devrunner/data
    restart: no
    environment:
      # Display environment
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - DISPLAY=${DISPLAY}
      # App environment
      - DATA_DIR=/home/devrunner/data
      - ENV=dev
      - EXPORT_DIR=${EXPORT_DIR}
      - INCREMENTAL=${INCREMENTAL}

volumes:
  dev-onedrive-data:
  dev-jr-auto-data:

x-podman:
  in_pod: false

